# Generated by Django 4.0.5 on 2022-09-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureValidators',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valid_feature_value', models.CharField(max_length=100, verbose_name='Валидное значение')),
            ],
            options={
                'verbose_name': 'Ключи характеристик',
                'verbose_name_plural': 'Ключи характеристик',
                'db_table': 'feature_validators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SparePartsUnitsFeatures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100, verbose_name='Имя ключа для категории')),
                ('feature_filter_name', models.CharField(max_length=100, verbose_name='Имя для фильтра')),
                ('unit', models.CharField(max_length=100, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Характеристики категории',
                'verbose_name_plural': 'Характеристики категории',
                'db_table': 'spare_parts_units_features',
                'managed': False,
            },
        ),
    ]
