# Generated by Django 4.0.5 on 2022-09-19 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '__first__'),
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('feature', models.ForeignKey(blank=True, db_column='feature', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='specs.sparepartsunitsfeatures', verbose_name='Характеристика')),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристики продуктов',
                'verbose_name_plural': 'Характеристики продуктов',
                'db_table': 'product_features',
            },
        ),
    ]
